FROM node:18 as build

WORKDIR /app

COPY ./client/package*.json ./

RUN npm install

COPY ./client .

# Set the API URL for production build
ENV REACT_APP_API_URL=/api/

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 