apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: fitness-app
  labels:
    app: backend
spec:
  replicas: 3  # Multiple replicas for load distribution
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: fitness-backend:latest  # We'll build this image
        imagePullPolicy: Never  # Use local image for minikube
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: fitness-app-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: fitness-app-config
              key: PORT
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: fitness-app-config
              key: MONGO_URI
        - name: JWT
          valueFrom:
            configMapKeyRef:
              name: fitness-app-config
              key: JWT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always 