apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fitness-app
  labels:
    app: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: http
    port: 4000
    targetPort: 4000
    protocol: TCP
  sessionAffinity: None 