apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-app-config
  namespace: fitness-app
data:
  NODE_ENV: "production"
  PORT: "4000"
  MONGO_URI: "mongodb://root:example@mongodb-service:27017/fitnessdb?authSource=admin"
  REACT_APP_API_URL: "http://backend-service:4000/api/" 