apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: fitness-app
  labels:
    app: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - name: mongodb-port
    port: 27017
    targetPort: 27017
    nodePort: 30001  # External access port
  sessionAffinity: None 